# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsCommentModule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsCommentModule

  target 'NewsCommentModuleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsCommentModuleUITests' do
    # Pods for testing
  end

 pod 'Masonry'

end
